"""add link table

Revision ID: d68abceb1633
Revises: d7ed18f08ecc
Create Date: 2022-10-07 10:35:01.425655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68abceb1633'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('short_link', sa.String(length=255), nullable=False),
    sa.Column('full_link', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('short_link')
    )
    op.create_index(op.f('ix_link_short_link'), 'link', ['short_link'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    # ### end Alembic commands ###
