version: '3.4'

services:
  db:
    container_name: db
    restart: always
    image: postgres
    volumes:
      - ./.postgres/.pgdata:/var/lib/postgresql/data
    network_mode: host
    env_file:
      - app/.env

  api:
    container_name: api
    restart: always
    build:
      context: ./
      dockerfile: ./deploy/Dockerfile
    network_mode: host
    depends_on:
      - db
    env_file:
      - app/.env

